name: superlative
description: A synchronous superlatives party game with player and display clients
version: 0.3.0
homepage: https://github.com/jmminch/superlative

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  shelf_web_socket: ^1.0.1
  shelf_static: ^1.1.0
  web_socket_channel: ^2.2.0
  stream_channel: ^2.1.4
  yaml: ^3.1.3

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
